
package com.yunyin.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "YunYinWebServiceOutImpl", targetNamespace = "http://www.ectongs.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface YunYinWebServiceOutImpl {


    /**
     * 
     * @param sXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsCargo", targetNamespace = "http://www.ectongs.com", className = "com.yunyin.client.WsCargo")
    @ResponseWrapper(localName = "wsCargoResponse", targetNamespace = "http://www.ectongs.com", className = "com.yunyin.client.WsCargoResponse")
    public String wsCargo(
        @WebParam(name = "sXml", targetNamespace = "")
        String sXml);

}
