
package com.yunyin.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "YunYinWebService", targetNamespace = "http://www.ectongs.com", wsdlLocation = "http://115.29.163.55:9186/service/yunying/wsCargo?wsdl")
public class YunYinWebService
    extends Service
{

    private final static URL YUNYINWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException YUNYINWEBSERVICE_EXCEPTION;
    private final static QName YUNYINWEBSERVICE_QNAME = new QName("http://www.ectongs.com", "YunYinWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://115.29.163.55:9186/service/yunying/wsCargo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YUNYINWEBSERVICE_WSDL_LOCATION = url;
        YUNYINWEBSERVICE_EXCEPTION = e;
    }

    public YunYinWebService() {
        super(__getWsdlLocation(), YUNYINWEBSERVICE_QNAME);
    }

    public YunYinWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), YUNYINWEBSERVICE_QNAME, features);
    }

    public YunYinWebService(URL wsdlLocation) {
        super(wsdlLocation, YUNYINWEBSERVICE_QNAME);
    }

    public YunYinWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YUNYINWEBSERVICE_QNAME, features);
    }

    public YunYinWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YunYinWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns YunYinWebServiceOutImpl
     */
    @WebEndpoint(name = "YunYinWebServiceOutImplPort")
    public YunYinWebServiceOutImpl getYunYinWebServiceOutImplPort() {
        return super.getPort(new QName("http://www.ectongs.com", "YunYinWebServiceOutImplPort"), YunYinWebServiceOutImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YunYinWebServiceOutImpl
     */
    @WebEndpoint(name = "YunYinWebServiceOutImplPort")
    public YunYinWebServiceOutImpl getYunYinWebServiceOutImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ectongs.com", "YunYinWebServiceOutImplPort"), YunYinWebServiceOutImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YUNYINWEBSERVICE_EXCEPTION!= null) {
            throw YUNYINWEBSERVICE_EXCEPTION;
        }
        return YUNYINWEBSERVICE_WSDL_LOCATION;
    }

}
